SELECT 
    USER_ID, 
    NICKNAME,
    CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) 전체주소,
    CONCAT(LEFT(TLNO, 3), '-', MID(TLNO, 4,4), '-', RIGHT(TLNO,4)) 전화번호
FROM USED_GOODS_USER as u, USED_GOODS_BOARD as b
WHERE USER_ID = WRITER_ID
GROUP BY USER_ID
HAVING COUNT(WRITER_ID) >= 3
order by USER_ID DESC