SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES
FROM REST_INFO a
    INNER JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES 
                FROM REST_INFO 
                GROUP BY FOOD_TYPE) b
WHERE a.FOOD_TYPE = b.FOOD_TYPE AND
      a.FAVORITES = b.FAVORITES
GROUP BY FOOD_TYPE
ORDER BY 
    FOOD_TYPE desc,
    FAVORITES desc;