SELECT t1.PRODUCT_CODE, sum(t1.PRICE * t2.SALES_AMOUNT) as SALES
FROM PRODUCT t1
    JOIN OFFLINE_SALE t2 
    ON t1.PRODUCT_ID = t2.PRODUCT_ID 
GROUP BY PRODUCT_CODE
ORDER BY SALES desc, PRODUCT_CODE 