SELECT 
  TITLE
  , reply.BOARD_ID BOARD_ID
  , reply.REPLY_ID REPLY_ID
  , reply.WRITER_ID WRITER_ID
  , reply.CONTENTS CONTENTS
  , DATE_FORMAT(reply.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD board
    , USED_GOODS_REPLY reply
WHERE board.BOARD_ID = reply.BOARD_ID
    AND board.CREATED_DATE LIKE '2022-10%'
ORDER BY reply.CREATED_DATE, TITLE