SELECT
    USER_ID,
    NICKNAME,
    SUM(PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD b
    JOIN USED_GOODS_USER u ON b.WRITER_ID = u.USER_ID
WHERE STATUS = 'DONE'
GROUP BY USER_ID
    HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES;