SELECT 
    MONTH(START_DATE) MONTH,
    h1.CAR_ID,
    COUNT(*) RECODRDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h1
    JOIN (
        SELECT 
            CAR_ID,
            COUNT(CAR_ID) RECODRDS
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE MONTH(START_DATE) BETWEEN '8' AND '10'
        GROUP BY CAR_ID
            HAVING COUNT(CAR_ID) > 4
    ) h2 ON h1.CAR_ID = h2.CAR_ID
 WHERE MONTH(START_DATE) BETWEEN '8' AND '10'
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC


        