SELECT DISTINCT c.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR c
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h ON c.CAR_ID = h.CAR_ID
WHERE CAR_TYPE = '세단'
    AND MONTH(START_DATE) >= 10 
ORDER BY CAR_ID DESC;
