SELECT  APNT_NO, PT_NAME, t1.PT_NO, t2.MCDP_CD, DR_NAME, APNT_YMD
FROM    PATIENT t1, DOCTOR t2, APPOINTMENT t3
WHERE   t1.PT_NO = t3.PT_NO 
    AND t2.DR_ID = t3.MDDR_ID
    AND t3.MCDP_CD = 'CS' 
    AND t3.APNT_CNCL_YN = 'N'
    AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
GROUP BY APNT_NO
ORDER BY APNT_YMD

