SELECT BOOK_ID, AUTHOR_NAME, date_format(PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM BOOK  t1
    JOIN AUTHOR  t2 
    ON t1.AUTHOR_ID = t2.AUTHOR_ID 
WHERE   CATEGORY = '경제'
ORDER BY PUBLISHED_DATE