# SELECT  t1.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, Round(Avg(t2.REVIEW_SCORE), 2) as SCORE
# FROM    REST_INFO t1, REST_REVIEW t2
# WHERE   t1.REST_ID = t2.REST_ID
#     AND ADDRESS LIKE '서울%'
# GROUP BY REST_ID
# ORDER BY SCORE desc, FAVORITES desc;
SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE 
FROM REST_INFO A
    ,REST_REVIEW B
WHERE A.REST_ID = B.REST_ID
AND A.ADDRESS LIKE '서울%'
GROUP BY A.REST_NAME
ORDER BY SCORE DESC, A.FAVORITES DESC;