# SELECT  REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, 
#         IfNull(SELECT Round(Avg(REVIEW_SCORE), 2) FROM REST_REVIEW WHERE REST_ID = REST_INFO.REST_ID, ) as SCORE
# FROM    REST_INFO
# WHERE   ADDRESS LIKE '서울%'
# ORDER BY SCORE desc, FAVORITES desc

SELECT  t1.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, Round(Avg(t2.REVIEW_SCORE), 2) as SCORE
FROM    REST_INFO t1, REST_REVIEW t2
WHERE   t1.REST_ID = t2.REST_ID
    AND ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE desc, FAVORITES desc
